In [2]:
#mm ... small edits by M. M.
# (#aaa #aaaa #aaaa ... "attention", "importance" marks, just for M. M.)
#mm-todo-tweak #aaaa

#mm
import torch
torch.set_printoptions(profile='short')
#%precision 2
# https://pytorch.org/docs/stable/generated/torch.set_printoptions.html
#torch.set_printoptions(precision=0)
torch.set_printoptions(threshold=7)
torch.set_printoptions(edgeitems=3)
torch.set_printoptions(edgeitems=1)


In [3]:
!conda env list

# conda environments:
#
base                     D:\conda
jupsci_nonpip310         D:\conda\envs\jupsci_nonpip310
pip310                *  D:\conda\envs\pip310
torch_nonpip310          D:\conda\envs\torch_nonpip310



In [4]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter("d:/ai/my235r/runs")

writer.flush()

In [5]:
# https://huggingface.co/fxmarty/tiny-testing-gpt2-remote-code

In [6]:
from transformers import AutoTokenizer, AutoModelWithLMHead   #,  TFAutoModel

tokenizer = AutoTokenizer.from_pretrained("fxmarty/tiny-testing-gpt2-remote-code")

####model = TFAutoModel.from_pretrained("fxmarty/tiny-testing-gpt2-remote-code" ) #  ,  from_pt=True)  
model = AutoModelWithLMHead.from_pretrained("fxmarty/tiny-testing-gpt2-remote-code" ) #  ,  from_pt=True)  

D:\conda\envs\pip310\lib\site-packages\transformers\models\auto\modeling_auto.py:1352: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  warnings.warn(


In [ ]:
# https://huggingface.co/sshleifer/tiny-gpt2

In [12]:
from transformers import AutoTokenizer, AutoModelForCausalLM  #, TFAutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("sshleifer/tiny-gpt2")

model =  AutoModelForCausalLM.from_pretrained("sshleifer/tiny-gpt2"  ) # ,  from_pt=True)

In [7]:

#model = GPT2LMHeadModel.from_pretrained('gpt2')  # or any other checkpoint
word_embeddings = model.transformer.wte.weight  # Word Token Embeddings 
position_embeddings = model.transformer.wpe.weight  # Word Position

In [8]:
from scipy import stats


In [9]:
stats.describe(word_embeddings.flatten().detach().numpy())


DescribeResult(nobs=32000, minmax=(-0.10435799, 0.082304895), mean=0.00017225943, variance=0.00039630984347471386, skewness=0.0001497342779539685, kurtosis=0.03427094952117349)

In [10]:
stats.describe(position_embeddings.flatten().detach().numpy())


DescribeResult(nobs=16384, minmax=(-0.07737117, 0.075206414), mean=0.00015542598, variance=0.0003896276789154535, skewness=-0.014906239080622023, kurtosis=-0.022284417011880553)

In [11]:
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(1000, 32)
    (wpe): Embedding(512, 32)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0): GPT2Block(
        (ln_1): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (1): GPT2Block(
        (ln_1): LayerNorm((32,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=

In [12]:
for layer in model.children():
    if hasattr(layer, 'out_features'):
        print(layer.out_features)

1000


In [13]:
#list(model.named_parameters())

In [14]:

for l in list(model.named_parameters()):
    print(l[0], ':', l[1].detach().numpy().shape)

transformer.wte.weight : (1000, 32)
transformer.wpe.weight : (512, 32)
transformer.h.0.ln_1.weight : (32,)
transformer.h.0.ln_1.bias : (32,)
transformer.h.0.attn.c_attn.weight : (32, 96)
transformer.h.0.attn.c_attn.bias : (96,)
transformer.h.0.attn.c_proj.weight : (32, 32)
transformer.h.0.attn.c_proj.bias : (32,)
transformer.h.0.ln_2.weight : (32,)
transformer.h.0.ln_2.bias : (32,)
transformer.h.0.mlp.c_fc.weight : (32, 128)
transformer.h.0.mlp.c_fc.bias : (128,)
transformer.h.0.mlp.c_proj.weight : (128, 32)
transformer.h.0.mlp.c_proj.bias : (32,)
transformer.h.1.ln_1.weight : (32,)
transformer.h.1.ln_1.bias : (32,)
transformer.h.1.attn.c_attn.weight : (32, 96)
transformer.h.1.attn.c_attn.bias : (96,)
transformer.h.1.attn.c_proj.weight : (32, 32)
transformer.h.1.attn.c_proj.bias : (32,)
transformer.h.1.ln_2.weight : (32,)
transformer.h.1.ln_2.bias : (32,)
transformer.h.1.mlp.c_fc.weight : (32, 128)
transformer.h.1.mlp.c_fc.bias : (128,)
transformer.h.1.mlp.c_proj.weight : (128, 32)
tra

In [15]:
word_embeddings.flatten().shape

torch.Size([32000])

In [16]:
import torch

ids = torch.tensor([5, 3], dtype=torch.int32)
x = torch.tensor([5, 3])


In [17]:
torch.stat

AttributeError: module 'torch' has no attribute 'stat'

In [18]:
model.state_dict()

OrderedDict([('transformer.wte.weight',
              tensor([[0.01,  ..., 0.05],
                      ...,
                      [0.01,  ..., 0.03]])),
             ('transformer.wpe.weight',
              tensor([[-0.02,  ..., -0.02],
                      ...,
                      [-0.03,  ...,  0.02]])),
             ('transformer.h.0.ln_1.weight', tensor([1.,  ..., 1.])),
             ('transformer.h.0.ln_1.bias', tensor([0.,  ..., 0.])),
             ('transformer.h.0.attn.bias',
              tensor([[[[ True,  ..., False],
                        ...,
                        [ True,  ...,  True]]]])),
             ('transformer.h.0.attn.masked_bias', tensor(-10000.)),
             ('transformer.h.0.attn.c_attn.weight',
              tensor([[ 0.01,  ..., -0.01],
                      ...,
                      [ 0.04,  ...,  0.02]])),
             ('transformer.h.0.attn.c_attn.bias', tensor([0.,  ..., 0.])),
             ('transformer.h.0.attn.c_proj.weight',
              te

In [ ]:
writer.add_graph(model,    input_to_model=ids  )
###writer.add_graph(model, input_to_model=torch.randn(1, 3, 224, 224))

# ModuleNotFoundError: No module named 'caffe2'


In [ ]:
import tensorflow as tf