In [ ]:
# by mm

In [24]:
import torch
import numpy as np
np.set_printoptions(precision=2)
torch.set_printoptions(profile='short')
%precision 2
# https://pytorch.org/docs/stable/generated/torch.set_printoptions.html

'%.2f'

In [38]:
torch.set_printoptions(precision=0)
torch.set_printoptions(threshold=5)
torch.set_printoptions(edgeitems=1)
###torch.set_printoptions(edgeitems=0)


In [39]:

x = torch.randn(2,3, 4)
print(x)


# pytorch Compute the maximum absolute value of x
def max_abs(x):
    return torch.max(torch.abs(x.detach().cpu().flatten()  )) .item()
    #np.abs(x.detach().numpy().flatten()).max()
    
max_abs(x)




tensor([[[-1,  ...,  0],
         ...,
         [-1,  ...,  1]],

        [[ 1,  ...,  1],
         ...,
         [ 0,  ..., -1]]])


2.48

In [ ]:
# https://huggingface.co/fxmarty/tiny-testing-gpt2-remote-code

In [31]:
from transformers import AutoTokenizer, AutoModelWithLMHead   #,  TFAutoModel

tokenizer = AutoTokenizer.from_pretrained("fxmarty/tiny-testing-gpt2-remote-code")

####model = TFAutoModel.from_pretrained("fxmarty/tiny-testing-gpt2-remote-code" ) #  ,  from_pt=True)  
model = AutoModelWithLMHead.from_pretrained("fxmarty/tiny-testing-gpt2-remote-code" ) #  ,  from_pt=True)  

D:\conda\envs\pip310\lib\site-packages\transformers\models\auto\modeling_auto.py:1352: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  warnings.warn(


In [ ]:
# https://huggingface.co/sshleifer/tiny-gpt2

In [43]:
from transformers import AutoTokenizer, AutoModelForCausalLM  #, TFAutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("sshleifer/tiny-gpt2")

model =  AutoModelForCausalLM.from_pretrained("sshleifer/tiny-gpt2"  ) # ,  from_pt=True)

In [41]:
https://huggingface.co/gpt2

SyntaxError: invalid syntax (3109400545.py, line 1)

In [45]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("gpt2")

model = AutoModelForCausalLM.from_pretrained("gpt2")

In [ ]:
#             ('transformer.h.0.attn.masked_bias', tensor(-10000.)),
             ('transformer.h.1.attn.masked_bias', tensor(-10000.)),
             ('transformer.h.4.attn.masked_bias', tensor(-10000.)),
        
        .attn.masked_bias


In [46]:
model.state_dict()

OrderedDict([('transformer.wte.weight',
              tensor([[-0,  ...,  0],
                      ...,
                      [ 0,  ...,  0]])),
             ('transformer.wpe.weight',
              tensor([[-0,  ...,  0],
                      ...,
                      [ 0,  ..., -0]])),
             ('transformer.h.0.ln_1.weight', tensor([0,  ..., 0])),
             ('transformer.h.0.ln_1.bias', tensor([-0,  ..., -0])),
             ('transformer.h.0.attn.bias',
              tensor([[[[ True,  ..., False],
                        ...,
                        [ True,  ...,  True]]]])),
             ('transformer.h.0.attn.masked_bias', tensor(-10000.)),
             ('transformer.h.0.attn.c_attn.weight',
              tensor([[-0,  ...,  0],
                      ...,
                      [-0,  ...,  0]])),
             ('transformer.h.0.attn.c_attn.bias', tensor([0,  ..., 0])),
             ('transformer.h.0.attn.c_proj.weight',
              tensor([[ 0,  ..., -0],
              

In [ ]:
model.named_parameters()

In [ ]:
print(1.54646456)
