In [5]:
import numpy as np

np.set_printoptions(suppress=True)

np.set_printoptions(threshold=20)
np.set_printoptions(threshold=400)

np.set_printoptions(edgeitems=10)

np.set_printoptions(precision=4)
#np.set_printoptions(precision=3)
np.set_printoptions(precision=2)
#np.set_printoptions(precision=1)
#np.set_printoptions(precision=0)

%precision 4
%precision 2


'%.2f'

In [7]:
import seaborn as sns
import matplotlib.pyplot as plt

# we'll use three operations
from einops import rearrange, reduce, repeat

In [6]:
import numpy as np

# start at 0, stop at 10, and generate 8 numbers
x = np.linspace(-2,2,3)
y = np.linspace(-2,2,3)

#x = np.random.randn(50)

xx,yy = np.meshgrid(x,y)
xx,yy

(array([[-2.,  0.,  2.],
        [-2.,  0.,  2.],
        [-2.,  0.,  2.]]),
 array([[-2., -2., -2.],
        [ 0.,  0.,  0.],
        [ 2.,  2.,  2.]]))

In [16]:
xxyy=[xx,yy]
#rearrange(x, 'b h w c -> b h w c').shape
rearrange(xxyy, 'b h w  -> b h w ').shape
x=rearrange(xxyy, 'b h w  ->  h w 1 b ')
rearrange(xxyy, 'b h w  ->  h w 1 b ').shape
x.shape

(3, 3, 1, 2)

In [17]:
x.ravel()

array([-2., -2.,  0., -2.,  2., -2., -2.,  0.,  0.,  0.,  2.,  0., -2.,
        2.,  0.,  2.,  2.,  2.])

In [18]:
x.flatten()

array([-2., -2.,  0., -2.,  2., -2., -2.,  0.,  0.,  0.,  2.,  0., -2.,
        2.,  0.,  2.,  2.,  2.])

In [23]:
np.linalg.norm(x, axis=(0,1))
np.linalg.norm(x, axis=(2,3))
np.linalg.norm(x, axis=(3))


array([[[2.83],
        [2.  ],
        [2.83]],

       [[2.  ],
        [0.  ],
        [2.  ]],

       [[2.83],
        [2.  ],
        [2.83]]])

In [20]:
np.linalg.norm(x[0,0,:,:])

2.83

In [15]:
np.linalg.norm?

Signature: np.linalg.norm(x, ord=None, axis=None, keepdims=False)
Docstring:
Matrix or vector norm.

This function is able to return one of eight different matrix norms,
or one of an infinite number of vector norms (described below), depending
on the value of the ``ord`` parameter.

Parameters
----------
x : array_like
    Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
    is None. If both `axis` and `ord` are None, the 2-norm of
    ``x.ravel`` will be returned.
ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
    Order of the norm (see table under ``Notes``). inf means numpy's
    `inf` object. The default is None.
axis : {None, int, 2-tuple of ints}, optional.
    If `axis` is an integer, it specifies the axis of `x` along which to
    compute the vector norms.  If `axis` is a 2-tuple, it specifies the
    axes that hold 2-D matrices, and the matrix norms of these matrices
    are computed.  If `axis` is None then either a vector norm (when `x`
    is 1