In [1]:
import torch


In [27]:
 A=torch.tensor([[0.0, 1], [1,0]]  )

In [30]:
 A=torch.tensor([[1,0.0], [0,-1]]  )

In [16]:
A=V

In [31]:
>>> L, V = torch.linalg.eig(A)


In [18]:
L

tensor([0.7071+0.7071j, 0.7071-0.7071j])

In [19]:
V

tensor([[7.0711e-01+0.0000j, 4.1392e-08-0.7071j],
        [-0.0000e+00-0.7071j, 7.0711e-01+0.0000j]])

In [32]:
(L.conj() * L)

#(L.conj() * L).norm()

tensor([1.+0.j, 1.+0.j])