In [1]:
import torch


In [27]:
 A=torch.tensor([[0.0, 1], [1,0]]  )

In [33]:
 A=torch.tensor([[1,0.0], [0,-1]]  )

In [16]:
A=V

In [57]:
 A=torch.tensor([[1,1], [0.0,1]]  )   # defect https://en.wikipedia.org/wiki/Defective_matrix

In [45]:
 ##A=torch.tensor([[1,1], [0,1]]  )   # defect https://en.wikipedia.org/wiki/Defective_matrix

In [58]:
A.dtype

torch.float32

In [47]:
V

tensor([[ 1.0000e+00+0.j, -1.0000e+00+0.j],
        [ 0.0000e+00+0.j,  1.1921e-07+0.j]])

In [52]:
S

tensor([1.4142e+00, 8.4294e-08])

In [59]:
>>> L, V = torch.linalg.eig(A)


In [60]:
torch.linalg.cond(V)

tensor(16777216.)

In [54]:
L

tensor([1.0000e+00+0.j, 1.1921e-07+0.j])

In [56]:
V

tensor([[1.0000+0.j, 0.7071+0.j],
        [0.0000+0.j, 0.7071+0.j]])

In [32]:
(L.conj() * L)

#(L.conj() * L).norm()

tensor([1.+0.j, 1.+0.j])

In [49]:
A=V

In [50]:
>>> U, S, Vh = torch.linalg.svd(A)


In [51]:
U

tensor([[ 1.0000e+00+0.j,  5.9605e-08+0.j],
        [-5.9605e-08+0.j,  1.0000e+00+0.j]])

In [52]:
S

tensor([1.4142e+00, 8.4294e-08])

In [41]:
Vh

tensor([[ 0.5257,  0.8507],
        [-0.8507,  0.5257]])