In [1]:
import torch


In [27]:
 A=torch.tensor([[0.0, 1], [1,0]]  )

In [33]:
 A=torch.tensor([[1,0.0], [0,-1]]  )

In [16]:
A=V

In [57]:
 A=torch.tensor([[1,1], [0.0,1]]  )   # defect https://en.wikipedia.org/wiki/Defective_matrix

In [45]:
 ##A=torch.tensor([[1,1], [0,1]]  )   # defect https://en.wikipedia.org/wiki/Defective_matrix

In [58]:
A.dtype

torch.float32

In [47]:
V

tensor([[ 1.0000e+00+0.j, -1.0000e+00+0.j],
        [ 0.0000e+00+0.j,  1.1921e-07+0.j]])

In [52]:
S

tensor([1.4142e+00, 8.4294e-08])

In [60]:
torch.linalg.cond(V)

tensor(16777216.)

In [59]:
>>> L, V = torch.linalg.eig(A)


In [60]:
torch.linalg.cond(V)

tensor(16777216.)

In [61]:
L

tensor([1.+0.j, 1.+0.j])

In [56]:
V

tensor([[1.0000+0.j, 0.7071+0.j],
        [0.0000+0.j, 0.7071+0.j]])

In [32]:
(L.conj() * L)

#(L.conj() * L).norm()

tensor([1.+0.j, 1.+0.j])

In [49]:
A=V

In [50]:
>>> U, S, Vh = torch.linalg.svd(A)


In [51]:
U

tensor([[ 1.0000e+00+0.j,  5.9605e-08+0.j],
        [-5.9605e-08+0.j,  1.0000e+00+0.j]])

In [52]:
S

tensor([1.4142e+00, 8.4294e-08])

In [41]:
Vh

tensor([[ 0.5257,  0.8507],
        [-0.8507,  0.5257]])

In [ ]:
#mm-begin-of-my-wrong-experim


In [32]:
#mm-begin-of-my-wrong-experim
x1 = torch.Tensor([0.0])               ; x1.requires_grad = True
x2 = torch.Tensor([0.0])                ; x2.requires_grad = True
w1 = torch.Tensor([3.0])             ; w1.requires_grad = True
w2 = torch.Tensor([4.0])                ; w2.requires_grad = True

w=torch.Tensor([w1,  w2]);  w.requires_grad =True

b = torch.Tensor([ -1.613735870195432]) ; b.requires_grad = True
n = x1*w1 + x2*w2 + b
#n= x1*w1 + b
#n= x1 + b
#o = torch.tanh(n)
o = n

#loss = sum((yout - ygt)**2 for ygt, yout in zip(ys, ypred))
loss=(o)**2

loss.backward()
print(loss)
print(b.grad)
####print(loss.grad)

tensor([2.6041], grad_fn=<PowBackward0>)
tensor([-3.2275])


In [40]:
import functorch

In [39]:
#mm wrong
##def pow_reducer(w1, w2):
def pow_reducer( x):
#     return x.pow(3).sum()

#    return (w1+ w2)**2
#    return (p[0].dot(p[1]))**2
#    return (p[0].dot(p[1]))
    
    return (w.dot(x))


###inputs = torch.tensor([[w1,w2],[x1,x2]])
inputs = torch.tensor([x1,x2])
print(inputs[1])
print(inputs)
###inputs = (w1, w2 )
h=torch.autograd.functional.hessian(pow_reducer, inputs)
h[0,0]
h
12
w
h
# tensor([[[[2.]]]])

tensor(0.)
tensor([0., 0.])


tensor([[0., 0.],
        [0., 0.]])

In [31]:
print(o.data.item())
o.backward()

print('---')
print('x2', x2.grad.item())
print('w2', w2.grad.item())
print('x1', x1.grad.item())
print('w1', w1.grad.item())

-1.6137359142303467


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.